export const countries = {
	"China": "סין",
	"Finland": "פינלנד",
	"France": "צרפת",
	"Germany": "גרמניה",
	"India": "הודו",
	"Iran": "איראן",
	"Israel": "ישראל",
	"Italy": "איטליה",
	"Japan": "יפן",
	"Lebanon": "לבנון",
	"Netherlands": "הולנד",
	"Palestine": "פלסטין",
	"Poland": "פולין",
	"Russia": "רוסיה",
	"Spain": "ספרד",
	"Turkey": "טורקיה",
	"UK": "בריטניה",
	"US": "ארצות הברית",
	"Ukraine": "אוקראינה",
	"United Arab Emirates": "איחוד האמירויות"
};
