export const countries = {
	"israel": { id: "Israel", hebrew: "ישראל", english: "Israel", languageDirection: "rtl", population: 9.2, softPower: 32, pressFreedom: 97 },
	"china": { id: "China", hebrew: "סין", english: "China", languageDirection: "ltr", population: 1439.3, softPower: 3, pressFreedom: 179 },
	"finland": { id: "Finland", hebrew: "פינלנד", english: "Finland", languageDirection: "ltr", softPower: 23, pressFreedom: 5 },
	"france": { id: "France", hebrew: "צרפת", english: "France", languageDirection: "ltr", population: 67.4, softPower: 4, pressFreedom: 24 },
	"germany": { id: "Germany", hebrew: "גרמניה", english: "Germany", languageDirection: "ltr", population: 83.2, softPower: 5, pressFreedom: 10 },
	"india": { id: "India", hebrew: "הודו", english: "India", languageDirection: "ltr", population: 1380.0, softPower: 29, pressFreedom: 161 },
	"iran": { id: "Iran", hebrew: "איראן", english: "Iran", languageDirection: "rtl", population: 84.0, softPower: 61, pressFreedom: 177 },
	"italy": { id: "Italy", hebrew: "איטליה", english: "Italy", languageDirection: "ltr", population: 60.4, softPower: 8, pressFreedom: 41 },
	"japan": { id: "Japan", hebrew: "יפן", english: "Japan", languageDirection: "ltr", population: 126.5, softPower: 6, pressFreedom: 68 },
	"lebanon": { id: "Lebanon", hebrew: "לבנון", english: "Lebanon", languageDirection: "rtl", population: 6.8, softPower: 67, pressFreedom: 106 },
	"netherlands": { id: "Netherlands", hebrew: "הולנד", english: "Netherlands", languageDirection: "ltr", population: 17.1, softPower: 17, pressFreedom: 6 },
	"palestine": { id: "Palestine", hebrew: "פלסטין", english: "Palestine", languageDirection: "rtl", population: 5.2, softPower: 123, pressFreedom: 170 },
	"poland": { id: "Poland", hebrew: "פולין", english: "Poland", languageDirection: "ltr", population: 37.8, softPower: 35, pressFreedom: 57 },
	"russia": { id: "Russia", hebrew: "רוסיה", english: "Russia", languageDirection: "ltr", population: 145.9, softPower: 16, pressFreedom: 164 },
	"spain": { id: "Spain", hebrew: "ספרד", english: "Spain", languageDirection: "ltr", population: 47.4, softPower: 15, pressFreedom: 19 },
	"turkey": { id: "Turkey", hebrew: "טורקיה", english: "Turkey", languageDirection: "ltr", population: 84.3, softPower: 25, pressFreedom: 165 },
	"uk": { id: "UK", hebrew: "בריטניה", english: "UK", languageDirection: "ltr", population: 67.2, softPower: 2, pressFreedom: 26 },
	"us": { id: "US", hebrew: "ארצות הברית", english: "US", languageDirection: "ltr", population: 331.0, softPower: 1, pressFreedom: 45 },
	"ukraine": { id: "Ukraine", hebrew: "אוקראינה", english: "Ukraine", languageDirection: "ltr", population: 44.1, softPower: 43, pressFreedom: 79 },
	"uae": { id: "United Arab Emirates", hebrew: "איחוד האמירויות", english: "UAE", languageDirection: "ltr", population: 9.9, softPower: 10, pressFreedom: 145 }
};