export const countries = {
	"israel": { id: "Israel", hebrew: "ישראל", english: "Israel", languageDirection: "rtl" },
	"china": { id: "China", hebrew: "סין", english: "China", languageDirection: "ltr" },
	"finland": { id: "Finland", hebrew: "פינלנד", english: "Finland", languageDirection: "ltr" },
	"france": { id: "France", hebrew: "צרפת", english: "France", languageDirection: "ltr" },
	"germany": { id: "Germany", hebrew: "גרמניה", english: "Germany", languageDirection: "ltr" },
	"india": { id: "India", hebrew: "הודו", english: "India", languageDirection: "ltr" },
	"iran": { id: "Iran", hebrew: "איראן", english: "Iran", languageDirection: "rtl" },
	"italy": { id: "Italy", hebrew: "איטליה", english: "Italy", languageDirection: "ltr" },
	"japan": { id: "Japan", hebrew: "יפן", english: "Japan", languageDirection: "ltr" },
	"lebanon": { id: "Lebanon", hebrew: "לבנון", english: "Lebanon", languageDirection: "rtl" },
	"netherlands": { id: "Netherlands", hebrew: "הולנד", english: "Netherlands", languageDirection: "ltr" },
	"palestine": { id: "Palestine", hebrew: "פלסטין", english: "Palestine", languageDirection: "rtl" },
	"poland": { id: "Poland", hebrew: "פולין", english: "Poland", languageDirection: "ltr" },
	"russia": { id: "Russia", hebrew: "רוסיה", english: "Russia", languageDirection: "ltr" },
	"spain": { id: "Spain", hebrew: "ספרד", english: "Spain", languageDirection: "ltr" },
	"turkey": { id: "Turkey", hebrew: "טורקיה", english: "Turkey", languageDirection: "ltr" },
	"uk": { id: "UK", hebrew: "בריטניה", english: "UK", languageDirection: "ltr" },
	"us": { id: "US", hebrew: "ארצות הברית", english: "US", languageDirection: "ltr" },
	"ukraine": { id: "Ukraine", hebrew: "אוקראינה", english: "Ukraine", languageDirection: "ltr" },
	"uae": { id: "UAE", hebrew: "איחוד האמירויות", english: "UAE", languageDirection: "ltr" }
};
